---
- name: Put certificate file in place
  copy:
    src: "{{ tower_cert_name }}"
    dest: "{{ tower_cert_directory }}{{ tower_cert_name }}"
    mode: 0600
    owner: awx
    group: awx
  notify: restart_tower

- name: Put key file in place
  copy:
    src: "{{ tower_key_name }}"
    dest: "{{ tower_cert_directory }}{{ tower_key_name }}"
    mode: 0600
    owner: awx
    group: awx
  notify: restart_tower
